# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# User types

class UserOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the User create method"""
    id: _str
    name: Optional[_str]
    password: Optional[_str]
    googleId: Optional[_str]
    profilePicture: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    scans: 'ScanCreateManyNestedWithoutRelationsInput'


class UserCreateInput(UserOptionalCreateInput):
    """Required arguments to the User create method"""
    email: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class UserOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the User create method, without relations"""
    id: _str
    name: Optional[_str]
    password: Optional[_str]
    googleId: Optional[_str]
    profilePicture: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class UserCreateWithoutRelationsInput(UserOptionalCreateWithoutRelationsInput):
    """Required arguments to the User create method, without relations"""
    email: _str

class UserConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'UserCreateWithoutRelationsInput'
    where: 'UserWhereUniqueInput'

class UserCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'


class UserCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['UserCreateWithoutRelationsInput', List['UserCreateWithoutRelationsInput']]
    connect: Union['UserWhereUniqueInput', List['UserWhereUniqueInput']]
    connect_or_create: Union['UserConnectOrCreateWithoutRelationsInput', List['UserConnectOrCreateWithoutRelationsInput']]

_UserWhereUnique_id_Input = TypedDict(
    '_UserWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

_UserWhereUnique_email_Input = TypedDict(
    '_UserWhereUnique_email_Input',
    {
        'email': '_str',
    },
    total=True
)

_UserWhereUnique_googleId_Input = TypedDict(
    '_UserWhereUnique_googleId_Input',
    {
        'googleId': '_str',
    },
    total=True
)

UserWhereUniqueInput = Union[
    '_UserWhereUnique_id_Input',
    '_UserWhereUnique_email_Input',
    '_UserWhereUnique_googleId_Input',
]


class UserUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    email: _str
    name: Optional[_str]
    password: Optional[_str]
    googleId: Optional[_str]
    profilePicture: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    scans: 'ScanUpdateManyWithoutRelationsInput'


class UserUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    email: _str
    name: Optional[_str]
    password: Optional[_str]
    googleId: Optional[_str]
    profilePicture: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class UserUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['UserCreateWithoutRelationsInput']
    connect: List['UserWhereUniqueInput']
    connect_or_create: List['UserConnectOrCreateWithoutRelationsInput']
    set: List['UserWhereUniqueInput']
    disconnect: List['UserWhereUniqueInput']
    delete: List['UserWhereUniqueInput']

    # TODO
    # update: List['UserUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['UserUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['UserScalarWhereInput']
    # upsert: List['UserUpserteWithWhereUniqueWithoutRelationsInput']


class UserUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'UserUpdateInput'
    # upsert: 'UserUpsertWithoutRelationsInput'


class UserUpsertInput(TypedDict):
    create: 'UserCreateInput'
    update: 'UserUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_User_id_OrderByInput = TypedDict(
    '_User_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_User_email_OrderByInput = TypedDict(
    '_User_email_OrderByInput',
    {
        'email': 'SortOrder',
    },
    total=True
)

_User_name_OrderByInput = TypedDict(
    '_User_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_User_password_OrderByInput = TypedDict(
    '_User_password_OrderByInput',
    {
        'password': 'SortOrder',
    },
    total=True
)

_User_googleId_OrderByInput = TypedDict(
    '_User_googleId_OrderByInput',
    {
        'googleId': 'SortOrder',
    },
    total=True
)

_User_profilePicture_OrderByInput = TypedDict(
    '_User_profilePicture_OrderByInput',
    {
        'profilePicture': 'SortOrder',
    },
    total=True
)

_User_createdAt_OrderByInput = TypedDict(
    '_User_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_User_updatedAt_OrderByInput = TypedDict(
    '_User_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

_User_RelevanceInner = TypedDict(
    '_User_RelevanceInner',
    {
        'fields': 'List[UserScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_User_RelevanceOrderByInput = TypedDict(
    '_User_RelevanceOrderByInput',
    {
        '_relevance': '_User_RelevanceInner',
    },
    total=True
)

UserOrderByInput = Union[
    '_User_id_OrderByInput',
    '_User_email_OrderByInput',
    '_User_name_OrderByInput',
    '_User_password_OrderByInput',
    '_User_googleId_OrderByInput',
    '_User_profilePicture_OrderByInput',
    '_User_createdAt_OrderByInput',
    '_User_updatedAt_OrderByInput',
    '_User_RelevanceOrderByInput',
]



# recursive User types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

UserRelationFilter = TypedDict(
    'UserRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class UserListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class UserInclude(TypedDict, total=False):
    """User relational arguments"""
    scans: Union[bool, 'FindManyScanArgsFromUser']


    

class UserIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    scans: Union[bool, 'FindManyScanArgsFromUserRecursive1']


class UserIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    scans: Union[bool, 'FindManyScanArgsFromUserRecursive2']


class UserIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    scans: Union[bool, 'FindManyScanArgsFromUserRecursive3']


class UserIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    scans: Union[bool, 'FindManyScanArgsFromUserRecursive4']


class UserIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class UserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyUserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class ScanIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive1']


class ScanIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive2']


class ScanIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive3']


class ScanIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive4']


class ScanIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class ScanArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'ScanIncludeFromScanRecursive1'


class ScanArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'ScanIncludeFromScanRecursive2'


class ScanArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'ScanIncludeFromScanRecursive3'


class ScanArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'ScanIncludeFromScanRecursive4'


class ScanArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyScanArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive1'


class FindManyScanArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive2'


class FindManyScanArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive3'


class FindManyScanArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive4'


class FindManyScanArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    


FindManyUserArgs = FindManyUserArgsFromUser
FindFirstUserArgs = FindManyUserArgsFromUser


    

class UserWhereInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[None, _str, 'types.StringFilter']
    googleId: Union[None, _str, 'types.StringFilter']
    profilePicture: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    scans: 'ScanListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive1', List['UserWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive1']
    OR: List['UserWhereInputRecursive1']
    NOT: List['UserWhereInputRecursive1']


class UserWhereInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[None, _str, 'types.StringFilter']
    googleId: Union[None, _str, 'types.StringFilter']
    profilePicture: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    scans: 'ScanListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive2', List['UserWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive2']
    OR: List['UserWhereInputRecursive2']
    NOT: List['UserWhereInputRecursive2']


class UserWhereInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[None, _str, 'types.StringFilter']
    googleId: Union[None, _str, 'types.StringFilter']
    profilePicture: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    scans: 'ScanListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive3', List['UserWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive3']
    OR: List['UserWhereInputRecursive3']
    NOT: List['UserWhereInputRecursive3']


class UserWhereInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[None, _str, 'types.StringFilter']
    googleId: Union[None, _str, 'types.StringFilter']
    profilePicture: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    scans: 'ScanListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive4', List['UserWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive4']
    OR: List['UserWhereInputRecursive4']
    NOT: List['UserWhereInputRecursive4']


class UserWhereInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[None, _str, 'types.StringFilter']
    googleId: Union[None, _str, 'types.StringFilter']
    profilePicture: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    scans: 'ScanListRelationFilter'



# aggregate User types


    

class UserScalarWhereWithAggregatesInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    googleId: Union[_str, 'types.StringWithAggregatesFilter']
    profilePicture: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive1']
    OR: List['UserScalarWhereWithAggregatesInputRecursive1']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive1']


class UserScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    googleId: Union[_str, 'types.StringWithAggregatesFilter']
    profilePicture: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive2']
    OR: List['UserScalarWhereWithAggregatesInputRecursive2']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive2']


class UserScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    googleId: Union[_str, 'types.StringWithAggregatesFilter']
    profilePicture: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive3']
    OR: List['UserScalarWhereWithAggregatesInputRecursive3']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive3']


class UserScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    googleId: Union[_str, 'types.StringWithAggregatesFilter']
    profilePicture: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive4']
    OR: List['UserScalarWhereWithAggregatesInputRecursive4']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive4']


class UserScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    googleId: Union[_str, 'types.StringWithAggregatesFilter']
    profilePicture: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class UserGroupByOutput(TypedDict, total=False):
    id: _str
    email: _str
    name: _str
    password: _str
    googleId: _str
    profilePicture: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    _sum: 'UserSumAggregateOutput'
    _avg: 'UserAvgAggregateOutput'
    _min: 'UserMinAggregateOutput'
    _max: 'UserMaxAggregateOutput'
    _count: 'UserCountAggregateOutput'


class UserAvgAggregateOutput(TypedDict, total=False):
    """User output for aggregating averages"""


class UserSumAggregateOutput(TypedDict, total=False):
    """User output for aggregating sums"""


class UserScalarAggregateOutput(TypedDict, total=False):
    """User output including scalar fields"""
    id: _str
    email: _str
    name: _str
    password: _str
    googleId: _str
    profilePicture: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


UserMinAggregateOutput = UserScalarAggregateOutput
UserMaxAggregateOutput = UserScalarAggregateOutput


class UserMaxAggregateInput(TypedDict, total=False):
    """User input for aggregating by max"""
    id: bool
    email: bool
    name: bool
    password: bool
    googleId: bool
    profilePicture: bool
    createdAt: bool
    updatedAt: bool


class UserMinAggregateInput(TypedDict, total=False):
    """User input for aggregating by min"""
    id: bool
    email: bool
    name: bool
    password: bool
    googleId: bool
    profilePicture: bool
    createdAt: bool
    updatedAt: bool


class UserNumberAggregateInput(TypedDict, total=False):
    """User input for aggregating numbers"""


UserAvgAggregateInput = UserNumberAggregateInput
UserSumAggregateInput = UserNumberAggregateInput


UserCountAggregateInput = TypedDict(
    'UserCountAggregateInput',
    {
        'id': bool,
        'email': bool,
        'name': bool,
        'password': bool,
        'googleId': bool,
        'profilePicture': bool,
        'createdAt': bool,
        'updatedAt': bool,
        '_all': bool,
    },
    total=False,
)

UserCountAggregateOutput = TypedDict(
    'UserCountAggregateOutput',
    {
        'id': int,
        'email': int,
        'name': int,
        'password': int,
        'googleId': int,
        'profilePicture': int,
        'createdAt': int,
        'updatedAt': int,
        '_all': int,
    },
    total=False,
)


UserKeys = Literal[
    'id',
    'email',
    'name',
    'password',
    'googleId',
    'profilePicture',
    'createdAt',
    'updatedAt',
    'scans',
]
UserScalarFieldKeys = Literal[
    'id',
    'email',
    'name',
    'password',
    'googleId',
    'profilePicture',
    'createdAt',
    'updatedAt',
]
UserScalarFieldKeysT = TypeVar('UserScalarFieldKeysT', bound=UserScalarFieldKeys)

UserRelationalFieldKeys = Literal[
        'scans',
    ]

# Scan types

class ScanOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Scan create method"""
    id: _str
    createdAt: datetime.datetime
    userId: Optional[_str]
    user: 'UserCreateNestedWithoutRelationsInput'


class ScanCreateInput(ScanOptionalCreateInput):
    """Required arguments to the Scan create method"""
    targetUrl: _str
    scanTimestamp: datetime.datetime
    results: 'fields.Json'


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class ScanOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Scan create method, without relations"""
    id: _str
    createdAt: datetime.datetime
    userId: Optional[_str]


class ScanCreateWithoutRelationsInput(ScanOptionalCreateWithoutRelationsInput):
    """Required arguments to the Scan create method, without relations"""
    targetUrl: _str
    scanTimestamp: datetime.datetime
    results: 'fields.Json'

class ScanConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'ScanCreateWithoutRelationsInput'
    where: 'ScanWhereUniqueInput'

class ScanCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'ScanCreateWithoutRelationsInput'
    connect: 'ScanWhereUniqueInput'
    connect_or_create: 'ScanConnectOrCreateWithoutRelationsInput'


class ScanCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['ScanCreateWithoutRelationsInput', List['ScanCreateWithoutRelationsInput']]
    connect: Union['ScanWhereUniqueInput', List['ScanWhereUniqueInput']]
    connect_or_create: Union['ScanConnectOrCreateWithoutRelationsInput', List['ScanConnectOrCreateWithoutRelationsInput']]

_ScanWhereUnique_id_Input = TypedDict(
    '_ScanWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

ScanWhereUniqueInput = _ScanWhereUnique_id_Input


class ScanUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    targetUrl: _str
    scanTimestamp: datetime.datetime
    results: 'fields.Json'
    createdAt: datetime.datetime
    user: 'UserUpdateOneWithoutRelationsInput'


class ScanUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    targetUrl: _str
    scanTimestamp: datetime.datetime
    results: 'fields.Json'
    createdAt: datetime.datetime


class ScanUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['ScanCreateWithoutRelationsInput']
    connect: List['ScanWhereUniqueInput']
    connect_or_create: List['ScanConnectOrCreateWithoutRelationsInput']
    set: List['ScanWhereUniqueInput']
    disconnect: List['ScanWhereUniqueInput']
    delete: List['ScanWhereUniqueInput']

    # TODO
    # update: List['ScanUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['ScanUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['ScanScalarWhereInput']
    # upsert: List['ScanUpserteWithWhereUniqueWithoutRelationsInput']


class ScanUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'ScanCreateWithoutRelationsInput'
    connect: 'ScanWhereUniqueInput'
    connect_or_create: 'ScanConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'ScanUpdateInput'
    # upsert: 'ScanUpsertWithoutRelationsInput'


class ScanUpsertInput(TypedDict):
    create: 'ScanCreateInput'
    update: 'ScanUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Scan_id_OrderByInput = TypedDict(
    '_Scan_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Scan_targetUrl_OrderByInput = TypedDict(
    '_Scan_targetUrl_OrderByInput',
    {
        'targetUrl': 'SortOrder',
    },
    total=True
)

_Scan_scanTimestamp_OrderByInput = TypedDict(
    '_Scan_scanTimestamp_OrderByInput',
    {
        'scanTimestamp': 'SortOrder',
    },
    total=True
)

_Scan_results_OrderByInput = TypedDict(
    '_Scan_results_OrderByInput',
    {
        'results': 'SortOrder',
    },
    total=True
)

_Scan_createdAt_OrderByInput = TypedDict(
    '_Scan_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_Scan_userId_OrderByInput = TypedDict(
    '_Scan_userId_OrderByInput',
    {
        'userId': 'SortOrder',
    },
    total=True
)

_Scan_RelevanceInner = TypedDict(
    '_Scan_RelevanceInner',
    {
        'fields': 'List[ScanScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Scan_RelevanceOrderByInput = TypedDict(
    '_Scan_RelevanceOrderByInput',
    {
        '_relevance': '_Scan_RelevanceInner',
    },
    total=True
)

ScanOrderByInput = Union[
    '_Scan_id_OrderByInput',
    '_Scan_targetUrl_OrderByInput',
    '_Scan_scanTimestamp_OrderByInput',
    '_Scan_results_OrderByInput',
    '_Scan_createdAt_OrderByInput',
    '_Scan_userId_OrderByInput',
    '_Scan_RelevanceOrderByInput',
]



# recursive Scan types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

ScanRelationFilter = TypedDict(
    'ScanRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class ScanListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class ScanInclude(TypedDict, total=False):
    """Scan relational arguments"""
    user: Union[bool, 'UserArgsFromScan']


    

class UserIncludeFromScan(TypedDict, total=False):
    """Relational arguments for Scan"""
    scans: Union[bool, 'FindManyScanArgsFromScanRecursive1']


class UserIncludeFromScanRecursive1(TypedDict, total=False):
    """Relational arguments for Scan"""
    scans: Union[bool, 'FindManyScanArgsFromScanRecursive2']


class UserIncludeFromScanRecursive2(TypedDict, total=False):
    """Relational arguments for Scan"""
    scans: Union[bool, 'FindManyScanArgsFromScanRecursive3']


class UserIncludeFromScanRecursive3(TypedDict, total=False):
    """Relational arguments for Scan"""
    scans: Union[bool, 'FindManyScanArgsFromScanRecursive4']


class UserIncludeFromScanRecursive4(TypedDict, total=False):
    """Relational arguments for Scan"""

    

class UserArgsFromScan(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromScanRecursive1(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromScanRecursive2(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromScanRecursive3(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromScanRecursive4(TypedDict, total=False):
    """Arguments for Scan"""
    
    

class FindManyUserArgsFromScan(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromScanRecursive1(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromScanRecursive2(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromScanRecursive3(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromScanRecursive4(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class ScanIncludeFromScan(TypedDict, total=False):
    """Relational arguments for Scan"""
    user: Union[bool, 'UserArgsFromScanRecursive1']


class ScanIncludeFromScanRecursive1(TypedDict, total=False):
    """Relational arguments for Scan"""
    user: Union[bool, 'UserArgsFromScanRecursive2']


class ScanIncludeFromScanRecursive2(TypedDict, total=False):
    """Relational arguments for Scan"""
    user: Union[bool, 'UserArgsFromScanRecursive3']


class ScanIncludeFromScanRecursive3(TypedDict, total=False):
    """Relational arguments for Scan"""
    user: Union[bool, 'UserArgsFromScanRecursive4']


class ScanIncludeFromScanRecursive4(TypedDict, total=False):
    """Relational arguments for Scan"""

    

class ScanArgsFromScan(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'ScanIncludeFromScanRecursive1'


class ScanArgsFromScanRecursive1(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'ScanIncludeFromScanRecursive2'


class ScanArgsFromScanRecursive2(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'ScanIncludeFromScanRecursive3'


class ScanArgsFromScanRecursive3(TypedDict, total=False):
    """Arguments for Scan"""
    include: 'ScanIncludeFromScanRecursive4'


class ScanArgsFromScanRecursive4(TypedDict, total=False):
    """Arguments for Scan"""
    
    

class FindManyScanArgsFromScan(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive1'


class FindManyScanArgsFromScanRecursive1(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive2'


class FindManyScanArgsFromScanRecursive2(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive3'


class FindManyScanArgsFromScanRecursive3(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    include: 'ScanIncludeFromScanRecursive4'


class FindManyScanArgsFromScanRecursive4(TypedDict, total=False):
    """Arguments for Scan"""
    take: int
    skip: int
    order_by: Union['ScanOrderByInput', List['ScanOrderByInput']]
    where: 'ScanWhereInput'
    cursor: 'ScanWhereUniqueInput'
    distinct: List['ScanScalarFieldKeys']
    


FindManyScanArgs = FindManyScanArgsFromScan
FindFirstScanArgs = FindManyScanArgsFromScan


    

class ScanWhereInput(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    targetUrl: Union[_str, 'types.StringFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeFilter']
    results: Union['fields.Json', 'types.JsonFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    userId: Union[None, _str, 'types.StringFilter']
    user: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['ScanWhereInputRecursive1', List['ScanWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['ScanWhereInputRecursive1']
    OR: List['ScanWhereInputRecursive1']
    NOT: List['ScanWhereInputRecursive1']


class ScanWhereInputRecursive1(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    targetUrl: Union[_str, 'types.StringFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeFilter']
    results: Union['fields.Json', 'types.JsonFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    userId: Union[None, _str, 'types.StringFilter']
    user: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['ScanWhereInputRecursive2', List['ScanWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['ScanWhereInputRecursive2']
    OR: List['ScanWhereInputRecursive2']
    NOT: List['ScanWhereInputRecursive2']


class ScanWhereInputRecursive2(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    targetUrl: Union[_str, 'types.StringFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeFilter']
    results: Union['fields.Json', 'types.JsonFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    userId: Union[None, _str, 'types.StringFilter']
    user: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['ScanWhereInputRecursive3', List['ScanWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['ScanWhereInputRecursive3']
    OR: List['ScanWhereInputRecursive3']
    NOT: List['ScanWhereInputRecursive3']


class ScanWhereInputRecursive3(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    targetUrl: Union[_str, 'types.StringFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeFilter']
    results: Union['fields.Json', 'types.JsonFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    userId: Union[None, _str, 'types.StringFilter']
    user: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['ScanWhereInputRecursive4', List['ScanWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['ScanWhereInputRecursive4']
    OR: List['ScanWhereInputRecursive4']
    NOT: List['ScanWhereInputRecursive4']


class ScanWhereInputRecursive4(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    targetUrl: Union[_str, 'types.StringFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeFilter']
    results: Union['fields.Json', 'types.JsonFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    userId: Union[None, _str, 'types.StringFilter']
    user: 'UserRelationFilter'



# aggregate Scan types


    

class ScanScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    targetUrl: Union[_str, 'types.StringWithAggregatesFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    results: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    userId: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ScanScalarWhereWithAggregatesInputRecursive1']
    OR: List['ScanScalarWhereWithAggregatesInputRecursive1']
    NOT: List['ScanScalarWhereWithAggregatesInputRecursive1']


class ScanScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    targetUrl: Union[_str, 'types.StringWithAggregatesFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    results: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    userId: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ScanScalarWhereWithAggregatesInputRecursive2']
    OR: List['ScanScalarWhereWithAggregatesInputRecursive2']
    NOT: List['ScanScalarWhereWithAggregatesInputRecursive2']


class ScanScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    targetUrl: Union[_str, 'types.StringWithAggregatesFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    results: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    userId: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ScanScalarWhereWithAggregatesInputRecursive3']
    OR: List['ScanScalarWhereWithAggregatesInputRecursive3']
    NOT: List['ScanScalarWhereWithAggregatesInputRecursive3']


class ScanScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    targetUrl: Union[_str, 'types.StringWithAggregatesFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    results: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    userId: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ScanScalarWhereWithAggregatesInputRecursive4']
    OR: List['ScanScalarWhereWithAggregatesInputRecursive4']
    NOT: List['ScanScalarWhereWithAggregatesInputRecursive4']


class ScanScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Scan arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    targetUrl: Union[_str, 'types.StringWithAggregatesFilter']
    scanTimestamp: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    results: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    userId: Union[_str, 'types.StringWithAggregatesFilter']



class ScanGroupByOutput(TypedDict, total=False):
    id: _str
    targetUrl: _str
    scanTimestamp: datetime.datetime
    results: 'fields.Json'
    createdAt: datetime.datetime
    userId: _str
    _sum: 'ScanSumAggregateOutput'
    _avg: 'ScanAvgAggregateOutput'
    _min: 'ScanMinAggregateOutput'
    _max: 'ScanMaxAggregateOutput'
    _count: 'ScanCountAggregateOutput'


class ScanAvgAggregateOutput(TypedDict, total=False):
    """Scan output for aggregating averages"""


class ScanSumAggregateOutput(TypedDict, total=False):
    """Scan output for aggregating sums"""


class ScanScalarAggregateOutput(TypedDict, total=False):
    """Scan output including scalar fields"""
    id: _str
    targetUrl: _str
    scanTimestamp: datetime.datetime
    results: 'fields.Json'
    createdAt: datetime.datetime
    userId: _str


ScanMinAggregateOutput = ScanScalarAggregateOutput
ScanMaxAggregateOutput = ScanScalarAggregateOutput


class ScanMaxAggregateInput(TypedDict, total=False):
    """Scan input for aggregating by max"""
    id: bool
    targetUrl: bool
    scanTimestamp: bool
    results: bool
    createdAt: bool
    userId: bool


class ScanMinAggregateInput(TypedDict, total=False):
    """Scan input for aggregating by min"""
    id: bool
    targetUrl: bool
    scanTimestamp: bool
    results: bool
    createdAt: bool
    userId: bool


class ScanNumberAggregateInput(TypedDict, total=False):
    """Scan input for aggregating numbers"""


ScanAvgAggregateInput = ScanNumberAggregateInput
ScanSumAggregateInput = ScanNumberAggregateInput


ScanCountAggregateInput = TypedDict(
    'ScanCountAggregateInput',
    {
        'id': bool,
        'targetUrl': bool,
        'scanTimestamp': bool,
        'results': bool,
        'createdAt': bool,
        'userId': bool,
        '_all': bool,
    },
    total=False,
)

ScanCountAggregateOutput = TypedDict(
    'ScanCountAggregateOutput',
    {
        'id': int,
        'targetUrl': int,
        'scanTimestamp': int,
        'results': int,
        'createdAt': int,
        'userId': int,
        '_all': int,
    },
    total=False,
)


ScanKeys = Literal[
    'id',
    'targetUrl',
    'scanTimestamp',
    'results',
    'createdAt',
    'userId',
    'user',
]
ScanScalarFieldKeys = Literal[
    'id',
    'targetUrl',
    'scanTimestamp',
    'results',
    'createdAt',
    'userId',
]
ScanScalarFieldKeysT = TypeVar('ScanScalarFieldKeysT', bound=ScanScalarFieldKeys)

ScanRelationalFieldKeys = Literal[
        'user',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields